# Generated by Django 5.2.17 on 2026-09-30 14:10

import django.core.validators
import django.db.models.deletion
import expedientes.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='número')),
                ('caratula', models.CharField(max_length=300, verbose_name='carátula')),
                ('fuero_juzgado', models.CharField(blank=True, max_length=200, verbose_name='fuero / juzgado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('tipo_proceso', models.CharField(blank=True, max_length=100, verbose_name='tipo de proceso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to=settings.AUTH_USER_MODEL, verbose_name='titular')),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=expedientes.models.ruta_adjunto)),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='descripción')),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'archivo adjunto',
                'verbose_name_plural': 'archivos adjuntos',
                'ordering': ['-subido'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3)),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='expedientes.expediente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('forma_pago', models.CharField(blank=True, max_length=100, verbose_name='forma de pago')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to='expedientes.expediente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('actor', 'Actor'), ('demandado', 'Demandado'), ('tercero', 'Tercero'), ('otro', 'Otro')], default='actor', max_length=20)),
                ('dni_cuit', models.CharField(blank=True, max_length=20, verbose_name='DNI / CUIT')),
                ('domicilio', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='expedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='PasoProcesal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('observaciones', models.TextField(blank=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'paso procesal',
                'verbose_name_plural': 'pasos procesales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplido', 'Cumplido')], default='pendiente', max_length=20)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimientos', to='expedientes.expediente')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='expediente',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('owner', 'numero'), name='numero_unico_por_titular'),
        ),
    ]
